# Generated by Django 4.2.30 on 2026-08-22 18:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_year', models.IntegerField()),
                ('filing_status', models.CharField(choices=[('SINGLE', 'Single'), ('MFJ', 'Married Filing Jointly'), ('MFS', 'Married Filing Separately'), ('HOH', 'Head of Household')], default='SINGLE', max_length=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_cases', to='tax.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary Taxpayer'), ('SPOUSE', 'Spouse'), ('DEPENDENT', 'Dependent')], max_length=20)),
                ('tax_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='tax.taxcase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employments', to='tax.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
