# Generated by Django 4.2.30 on 2026-08-22 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('FORM_1040', 'Form 1040'), ('GOVERNMENT_ID', 'Government ID'), ('W2', 'W-2')], max_length=30)),
                ('tax_year', models.PositiveIntegerField()),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tax.employment')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tax.person')),
                ('tax_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='tax.taxcase')),
            ],
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('employment__isnull', False)), fields=('tax_case', 'person', 'employment', 'document_type', 'tax_year'), name='unique_employment_requirement'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('employment__isnull', True), ('person__isnull', False)), fields=('tax_case', 'person', 'document_type', 'tax_year'), name='unique_person_requirement'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(condition=models.Q(('employment__isnull', True), ('person__isnull', True)), fields=('tax_case', 'document_type', 'tax_year'), name='unique_tax_case_requirement'),
        ),
    ]
