# Generated by Django 4.2.30 on 2026-08-23 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_requirement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('storage_key', models.CharField(max_length=500)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('processing_status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('tax_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tax.taxcase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
