# Generated by Django 4.2.30 on 2026-08-25 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('FORM_1040', 'Form 1040'), ('GOVERNMENT_ID', 'Government ID'), ('W2', 'W-2')], max_length=30)),
                ('tax_year', models.PositiveIntegerField(blank=True, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLASSIFIED', 'Classified'), ('REVIEW_REQUIRED', 'Review Required'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_current', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='tax.document')),
                ('employment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_classifications', to='tax.employment')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_classifications', to='tax.person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
