# Generated by Django 4.2.30 on 2026-08-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_documentclassification'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentclassification',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='unique_current_classification_per_document'),
        ),
    ]
