# Generated by Django 4.2.30 on 2026-08-25 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_documentclassification_unique_current_classification_per_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementDocumentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('REVIEW_REQUIRED', 'Review Required'), ('REJECTED', 'Rejected')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('match_reason', models.TextField(blank=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_matches', to='tax.documentclassification')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_matches', to='tax.document')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_matches', to='tax.requirement')),
            ],
        ),
        migrations.AddConstraint(
            model_name='requirementdocumentmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('requirement',), name='unique_active_match_per_requirement'),
        ),
    ]
