# Generated by Django 4.2.30 on 2026-08-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0006_requirementdocumentmatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementdocumentmatch',
            name='status',
            field=models.CharField(choices=[('MATCHED', 'Matched'), ('REVIEW_REQUIRED', 'Review Required'), ('REJECTED', 'Rejected'), ('SUPERSEDED', 'Superseded')], max_length=20),
        ),
    ]
