# Generated by Django 4.2.30 on 2026-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_alter_requirementdocumentmatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentclassification',
            name='document_type',
            field=models.CharField(choices=[('FORM_1040', 'Form 1040'), ('GOVERNMENT_ID', 'Government ID'), ('W2', 'W-2'), ('UNKNOWN', 'Unknown')], max_length=30),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='document_type',
            field=models.CharField(choices=[('FORM_1040', 'Form 1040'), ('GOVERNMENT_ID', 'Government ID'), ('W2', 'W-2'), ('UNKNOWN', 'Unknown')], max_length=30),
        ),
    ]
